---
language: c++

sudo: enabled

git:
  depth: 5

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

# Setup cache
cache:
  directories:
    - build
    - .mtime_cache

# Setup build matrix and dependencies
before_install:
  - eval "${MATRIX_EVAL}"
  - gem install --no-ri --no-rdoc mtime_cache
  - sudo add-apt-repository -y ppa:rexut/recoil
  - sudo apt-get update
  - sudo apt-get install -y libboost1.63-dev libboost1.63-all-dev
  - sudo apt-get install -y libmysqlclient-dev

# Build steps
script:
  - $CXX --version
  - mtime_cache src/**/*.{%{cpp}} -c .mtime_cache/cache.json
  - mkdir -p build
  - cd build
  - cmake .. -DSAPPHIRE_BOOST_VER="1.63.0" && make -j 3
  - cd ..
  - bash sql_import.sh
